configuration: Release  
  
build:
  project-converter: Converter/GFWToVBNetConverter/GFWToVBNetConverter.sln
  project-sample: Test\GFAWIN-Samples\GFAWIN-Samples.sln
  
artifacts:
  - path: 'Converter\GFWToVBNetConverter\bin\$(configuration)'
    name: GFWToVBNetConverter
    type: zip
  - path: 'Test\GFAWIN-Samples\bin\$(configuration)'
    name: GFAWIN-Samples
    type: zip
    
